
// Map of nationalities to ISO 3166-1 alpha-2 country codes
// for use with the react-country-flag component
export const nationalityToCountryCode: Record<string, string> = {
  "Afghan": "AF",
  "Albanian": "AL",
  "Algerian": "DZ",
  "American": "US",
  "Andorran": "AD",
  "Angolan": "AO",
  "Antiguan": "AG",
  "Argentine": "AR",
  "Armenian": "AM",
  "Australian": "AU",
  "Austrian": "AT",
  "Azerbaijani": "AZ",
  "Bahamian": "BS",
  "Bahraini": "BH",
  "Bangladeshi": "BD",
  "Barbadian": "BB",
  "Belarusian": "BY",
  "Belgian": "BE",
  "Belizean": "BZ",
  "Beninese": "BJ",
  "Bhutanese": "BT",
  "Bolivian": "BO",
  "Bosnian": "BA",
  "Motswana": "BW", // From Botswana
  "Brazilian": "BR",
  "British": "GB",
  "Bruneian": "BN",
  "Bulgarian": "BG",
  "Burkinabe": "BF",
  "Burmese": "MM",
  "Burundian": "BI",
  "Cambodian": "KH",
  "Cameroonian": "CM",
  "Canadian": "CA",
  "Cape Verdean": "CV",
  "Central African": "CF",
  "Chadian": "TD",
  "Chilean": "CL",
  "Chinese": "CN",
  "Colombian": "CO",
  "Comorian": "KM",
  "Congolese": "CD", // Democratic Republic of Congo
  "Costa Rican": "CR",
  "Croatian": "HR",
  "Cuban": "CU",
  "Cypriot": "CY",
  "Czech": "CZ",
  "Danish": "DK",
  "Djiboutian": "DJ",
  "Dominican": "DO",
  "Dutch": "NL",
  "East Timorese": "TL",
  "Ecuadorian": "EC",
  "Egyptian": "EG",
  "Emirati": "AE",
  "Equatorial Guinean": "GQ",
  "Eritrean": "ER",
  "Estonian": "EE",
  "Ethiopian": "ET",
  "Fijian": "FJ",
  "Filipino": "PH",
  "Finnish": "FI",
  "French": "FR",
  "Gabonese": "GA",
  "Gambian": "GM",
  "Georgian": "GE",
  "German": "DE",
  "Ghanaian": "GH",
  "Greek": "GR",
  "Grenadian": "GD",
  "Guatemalan": "GT",
  "Guinean": "GN",
  "Guyanese": "GY",
  "Haitian": "HT",
  "Honduran": "HN",
  "Hungarian": "HU",
  "Icelandic": "IS",
  "Indian": "IN",
  "Indonesian": "ID",
  "Iranian": "IR",
  "Iraqi": "IQ",
  "Irish": "IE",
  "Israeli": "IL",
  "Italian": "IT",
  "Ivorian": "CI",
  "Jamaican": "JM",
  "Japanese": "JP",
  "Jordanian": "JO",
  "Kazakhstani": "KZ",
  "Kenyan": "KE",
  "Kittian": "KN",
  "Kuwaiti": "KW",
  "Kyrgyz": "KG",
  "Laotian": "LA",
  "Latvian": "LV",
  "Lebanese": "LB",
  "Liberian": "LR",
  "Libyan": "LY",
  "Liechtensteiner": "LI",
  "Lithuanian": "LT",
  "Luxembourgish": "LU",
  "Macedonian": "MK",
  "Malagasy": "MG",
  "Malawian": "MW",
  "Malaysian": "MY",
  "Maldivian": "MV",
  "Malian": "ML",
  "Maltese": "MT",
  "Marshallese": "MH",
  "Mauritanian": "MR",
  "Mauritian": "MU",
  "Mexican": "MX",
  "Micronesian": "FM",
  "Moldovan": "MD",
  "Monacan": "MC",
  "Mongolian": "MN",
  "Montenegrin": "ME",
  "Moroccan": "MA",
  "Mozambican": "MZ",
  "Namibian": "NA",
  "Nauruan": "NR",
  "Nepalese": "NP",
  "New Zealander": "NZ",
  "Nicaraguan": "NI",
  "Nigerian": "NG",
  "Norwegian": "NO",
  "Omani": "OM",
  "Pakistani": "PK",
  "Palauan": "PW",
  "Panamanian": "PA",
  "Papua New Guinean": "PG",
  "Paraguayan": "PY",
  "Peruvian": "PE",
  "Polish": "PL",
  "Portuguese": "PT",
  "Qatari": "QA",
  "Romanian": "RO",
  "Russian": "RU",
  "Rwandan": "RW",
  "Saint Lucian": "LC",
  "Salvadoran": "SV",
  "Samoan": "WS",
  "San Marinese": "SM",
  "Sao Tomean": "ST",
  "Saudi": "SA",
  "Senegalese": "SN",
  "Serbian": "RS",
  "Seychellois": "SC",
  "Sierra Leonean": "SL",
  "Singaporean": "SG",
  "Slovakian": "SK",
  "Slovenian": "SI",
  "Solomon Islander": "SB",
  "Somali": "SO",
  "South African": "ZA",
  "South Korean": "KR",
  "Spanish": "ES",
  "Sri Lankan": "LK",
  "Sudanese": "SD",
  "Surinamese": "SR",
  "Swazi": "SZ",
  "Swedish": "SE",
  "Swiss": "CH",
  "Syrian": "SY",
  "Taiwanese": "TW",
  "Tajik": "TJ",
  "Tanzanian": "TZ",
  "Thai": "TH",
  "Togolese": "TG",
  "Tongan": "TO",
  "Trinidadian": "TT",
  "Tunisian": "TN",
  "Turkish": "TR",
  "Tuvaluan": "TV",
  "Ugandan": "UG",
  "Ukrainian": "UA",
  "Uruguayan": "UY",
  "Uzbekistani": "UZ",
  "Vatican": "VA",
  "Venezuelan": "VE",
  "Vietnamese": "VN",
  "Vincentian": "VC",
  "Yemeni": "YE",
  "Zambian": "ZM",
  "Zimbabwean": "ZW",
};

/**
 * Gets the country code for a given nationality
 * @param nationality The nationality string
 * @returns The ISO 3166-1 alpha-2 country code or undefined if not found
 */
export const getCountryCodeFromNationality = (nationality: string): string | undefined => {
  return nationalityToCountryCode[nationality];
};
