// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieariyszxnffkktxaehz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYXJpeXN6eG5mZmtrdHhhZWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODU5NTYsImV4cCI6MjA1NzI2MTk1Nn0.If4O3AqUaziJOGvZyrASoiAYrmgKO31TwAYwmhrwfvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);